"""cascade behaviour added

Revision ID: 0d2d1c23c799
Revises: d2317057fef5
Create Date: 2025-06-06 10:08:49.084981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2d1c23c799'
down_revision: Union[str, None] = 'd2317057fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_documents_doc_id_fkey', 'access_documents', type_='foreignkey')
    op.drop_constraint('access_documents_user_id_fkey', 'access_documents', type_='foreignkey')
    op.create_foreign_key(None, 'access_documents', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_documents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('directories_parent_id_fkey', 'directories', type_='foreignkey')
    op.drop_constraint('directories_user_id_fkey', 'directories', type_='foreignkey')
    op.create_foreign_key(None, 'directories', 'directories', ['parent_id'], ['dir_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'directories', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('documents_directory_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_user_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'directories', ['directory_id'], ['dir_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_user_id_fkey', 'documents', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('documents_directory_id_fkey', 'documents', 'directories', ['directory_id'], ['dir_id'])
    op.drop_constraint(None, 'directories', type_='foreignkey')
    op.drop_constraint(None, 'directories', type_='foreignkey')
    op.create_foreign_key('directories_user_id_fkey', 'directories', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('directories_parent_id_fkey', 'directories', 'directories', ['parent_id'], ['dir_id'])
    op.drop_constraint(None, 'access_documents', type_='foreignkey')
    op.drop_constraint(None, 'access_documents', type_='foreignkey')
    op.create_foreign_key('access_documents_user_id_fkey', 'access_documents', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('access_documents_doc_id_fkey', 'access_documents', 'documents', ['doc_id'], ['doc_id'])
    # ### end Alembic commands ###
