"""access_document_created

Revision ID: 3c2d06d9586d
Revises: 3d65f730b989
Create Date: 2025-05-23 09:40:28.110002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2d06d9586d'
down_revision: Union[str, None] = '3d65f730b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_documents',
    sa.Column('access_doc_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('access_doc_id'),
    sa.UniqueConstraint('doc_id', 'user_id', name='unique_doc_user_access')
    )
    op.create_unique_constraint(None, 'directories', ['dir_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directories', type_='unique')
    op.drop_table('access_documents')
    # ### end Alembic commands ###
