"""dirs and document created

Revision ID: 3d65f730b989
Revises: fedf53dd8925
Create Date: 2025-05-19 10:14:11.401118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d65f730b989'
down_revision: Union[str, None] = 'fedf53dd8925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('dir_id', sa.String(length=36), nullable=False),
    sa.Column('dir_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.dir_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dir_id')
    )
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('doc_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.dir_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('doc_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('directories')
    # ### end Alembic commands ###
