"""modified access document2

Revision ID: 4f4ec622d0cc
Revises: 32436975f31b
Create Date: 2025-05-23 10:40:03.724769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4ec622d0cc'
down_revision: Union[str, None] = '32436975f31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_documents', sa.Column('permission_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_documents', 'permission_type')
    # ### end Alembic commands ###
