"""is_stared added in directory

Revision ID: 9fe72edd3a3a
Revises: d6cc6987da9f
Create Date: 2025-06-08 10:08:08.088511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe72edd3a3a'
down_revision: Union[str, None] = 'd6cc6987da9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('is_stared', sa.Boolean(), nullable=False,server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directories', 'is_stared')
    # ### end Alembic commands ###
