"""is_stared fill added and update some contraints

Revision ID: d6cc6987da9f
Revises: 0d2d1c23c799
Create Date: 2025-06-08 09:06:17.806638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cc6987da9f'
down_revision: Union[str, None] = '0d2d1c23c799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('directories_dir_name_key', 'directories', type_='unique')
    op.create_unique_constraint('unique_user_dir_name', 'directories', ['user_id', 'dir_name'])
    op.add_column('documents', sa.Column('is_stared', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.drop_constraint('documents_doc_name_key', 'documents', type_='unique')
    op.create_unique_constraint('unique_user_doc_name', 'documents', ['user_id', 'doc_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_doc_name', 'documents', type_='unique')
    op.create_unique_constraint('documents_doc_name_key', 'documents', ['doc_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'is_stared')
    op.drop_constraint('unique_user_dir_name', 'directories', type_='unique')
    op.create_unique_constraint('directories_dir_name_key', 'directories', ['dir_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
