"""constraint updated for document name

Revision ID: feaf36004a45
Revises: 37c16e256dcb
Create Date: 2025-06-19 19:03:15.347872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feaf36004a45'
down_revision: Union[str, None] = '37c16e256dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_doc_name', 'documents', type_='unique')
    op.create_unique_constraint('unique_user_doc_name', 'documents', ['user_id', 'directory_id', 'doc_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_doc_name', 'documents', type_='unique')
    op.create_unique_constraint('unique_user_doc_name', 'documents', ['user_id', 'doc_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
